<?php
/*
广州综合,id=zhonghe
广州新闻,id=xinwen
广州竞赛,id=jingsai
广州影视,id=yingshi
广州法治,id=fazhi
广州南国都市,id=shenghuo
*/
$id=$_GET['id'];
$url='https://www.gztv.com/gztv/api/tv/'.$id;
$ch=curl_init();
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
$data=curl_exec($ch);
curl_close($ch);
$re=json_decode($data)->data;
header('location:'.$re);
?>
